name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SetUp Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dannicool
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install devDependencies
        run: npm install --only=dev

      - name: Generate changelog
        run: npm run release

      - name: Build and Push Docker Image
        run: |
          docker build . -t dannicool/docker-wechatbot-webhook:latest
          docker push dannicool/docker-wechatbot-webhook:latest

      - name: commit and tag release
        run: |
          git config --global user.email "contact@danni.cool"
          git config --global user.name "gitHubCi"
          git add .
          git commit -m "Commit changes for release"
          git push origin main
          git tag v$(node -p "require('./package.json').version")
          git push --tags

      - name: 创建GitHub Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(node -p "require('./package.json').version")
          release_name: Release v$(node -p "require('./package.json').version")
          body: 更新内容参见 [CHANGELOG](https://github.com/danni-cool/docker-wechat-roomBot/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false
