name: Release and Push Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: docker-wechatbot-webhook
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Refactor","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false}]'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dannicool
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dannicool/docker-wechatbot-webhook:latest
          platforms: linux/amd64,linux/arm64
      
      # Setup .npmrc file to publish to npm
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://registry.npmjs.org'
      # - run: npm ci

      # # New step to copy docs/cli.readme.md to readme.md
      # - name: replace cli README.md to README.md
      #   run: cp ./docs/cli.README.md ./README.md

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}