name: Release-Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, '[release tag]') == true
    runs-on: ubuntu-latest

    steps:
      - name: 创建GitHub Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 更新内容参见 [CHANGELOG](https://github.com/danni-cool/docker-wechatbot-webhook/blob/main/CHANGELOG.md)
          draft: false
          prerelease: false
